name: "mbedtls libs mbedtls-2.28-use-hardcode-entropy (cache+build)"
description: "Restore/build/save third_party/mbedtls/library for mbedtls-2.28-use-hardcode-entropy"
runs:
  using: "composite"
  steps:
    - name: restore cache
      id: r
      uses: actions/cache/restore@v4
      with:
        path: third_party/mbedtls/library
        key: mbedtls-2.28-use-hardcode-entropy

    - name: prepare third_party/mbedtls/library (build if needed)
      shell: bash
      run: |
        set -Eeuo pipefail
        need=0
        for f in libmbedtls.a libmbedx509.a libmbedcrypto.a; do
          [ -f third_party/mbedtls/library/$f ] || need=1
        done

        if [ "$need" = 0 ]; then
          echo "✓ cache hit: all libs present"; exit 0
        fi

        echo "→ cache miss: build mbedtls mbedtls-2.28-use-hardcode-entropy"
        if ! command -v arm-none-eabi-gcc >/dev/null; then
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends gcc-arm-none-eabi binutils-arm-none-eabi make
        fi

        rm -rf third_party/mbedtls
        git clone --depth=1 --branch mbedtls-2.28-use-hardcode-entropy --single-branch \
          https://github.com/jeffrey-minwei/mbedtls third_party/mbedtls

        sed -ri 's/^(\s*)#define\s+MBEDTLS_FS_IO/\1\/\/ #define MBEDTLS_FS_IO/' third_party/mbedtls/include/mbedtls/config.h
        sed -ri 's/^(\s*)#define\s+MBEDTLS_HAVE_TIME_DATE/\1\/\/ #define MBEDTLS_HAVE_TIME_DATE/' third_party/mbedtls/include/mbedtls/config.h
        sed -ri 's/^(\s*)#define\s+MBEDTLS_TIMING_C/\1\/\/ #define MBEDTLS_TIMING_C/' third_party/mbedtls/include/mbedtls/config.h
        sed -ri 's/^(\s*)#define\s+MBEDTLS_PSA_ITS_FILE_C/\1\/\/ #define MBEDTLS_PSA_ITS_FILE_C/' third_party/mbedtls/include/mbedtls/config.h
        sed -ri 's/^(\s*)#define\s+MBEDTLS_PSA_CRYPTO_STORAGE_C/\1\/\/ #define MBEDTLS_PSA_CRYPTO_STORAGE_C/' third_party/mbedtls/include/mbedtls/config.h
        sed -ri 's/^(\s*)#define\s+MBEDTLS_NET_C/\1\/\/ #define MBEDTLS_NET_C/' third_party/mbedtls/include/mbedtls/config.h

        make -C third_party/mbedtls lib CC=arm-none-eabi-gcc AR=arm-none-eabi-ar \
          CFLAGS='-DMBEDTLS_NO_PLATFORM_ENTROPY -DMBEDTLS_NO_DEFAULT_ENTROPY_SOURCES -DMBEDTLS_TEST_NULL_ENTROPY'

        for f in libmbedtls.a libmbedx509.a libmbedcrypto.a; do
          test -f third_party/mbedtls/library/$f || { echo "MISSING: $f"; exit 1; }
        done
        echo "✓ built: libs ready"

    - name: save cache (if built)
      if: steps.r.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: third_party/mbedtls/library
        key: mbedtls-2.28-use-hardcode-entropy